# Generated by Django 6.0.4 on 2026-05-11
#
# Squashed migration replacing:
# - 0002_carlisting_brand_fk_carlisting_model_fk
# - 0003_populate_brand_model_fks
# - 0004_rename_brand_model_fks
# - 0005_add_validators_and_city_index

from decimal import Decimal

import django.db.models.deletion
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models
from django.utils.text import slugify


def populate_fks(apps, schema_editor):
    CarListing = apps.get_model('listings', 'CarListing')
    CarBrand = apps.get_model('cars', 'CarBrand')
    CarModel = apps.get_model('cars', 'CarModel')

    for listing in CarListing.objects.all():
        if not listing.brand or not listing.model:
            raise ValueError(
                f"Cannot migrate listing {listing.pk}: missing brand/model text values."
            )

        brand = CarBrand.objects.filter(name__iexact=listing.brand).first()
        if not brand:
            brand = CarBrand.objects.create(
                name=listing.brand.strip(),
                slug=slugify(listing.brand),
                is_active=True,
            )

        model = CarModel.objects.filter(brand=brand, name__iexact=listing.model).first()
        if not model:
            model = CarModel.objects.create(
                brand=brand,
                name=listing.model.strip(),
                is_active=True,
            )

        listing.brand_fk_id = brand.id
        listing.model_fk_id = model.id
        listing.save(update_fields=['brand_fk', 'model_fk'])


def reverse_populate_fks(apps, schema_editor):
    CarListing = apps.get_model('listings', 'CarListing')
    CarListing.objects.update(brand_fk=None, model_fk=None)


class Migration(migrations.Migration):
    replaces = [
        ('listings', '0002_carlisting_brand_fk_carlisting_model_fk'),
        ('listings', '0003_populate_brand_model_fks'),
        ('listings', '0004_rename_brand_model_fks'),
        ('listings', '0005_add_validators_and_city_index'),
    ]

    dependencies = [
        ('cars', '0001_initial'),
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlisting',
            name='brand_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='listings',
                to='cars.carbrand',
            ),
        ),
        migrations.AddField(
            model_name='carlisting',
            name='model_fk',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='listings',
                to='cars.carmodel',
            ),
        ),
        migrations.RunPython(populate_fks, reverse_populate_fks),
        migrations.RemoveField(
            model_name='carlisting',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='carlisting',
            name='model',
        ),
        migrations.RenameField(
            model_name='carlisting',
            old_name='brand_fk',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='carlisting',
            old_name='model_fk',
            new_name='model',
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='brand',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='listings',
                to='cars.carbrand',
            ),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='model',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='listings',
                to='cars.carmodel',
            ),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[MinValueValidator(Decimal('0'))],
            ),
        ),
        migrations.AlterField(
            model_name='carlisting',
            name='year',
            field=models.PositiveIntegerField(
                validators=[
                    MinValueValidator(1886),
                    MaxValueValidator(2100),
                ]
            ),
        ),
    ]

